# Generated by Django 4.0 on 2021-12-29 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 12, 22, 58, 318978, tzinfo=utc)),
        ),
    ]
